name: flutter_ppkd_b3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0   # ← tambahkan ini
  material_symbols_icons: ^4.2750.0
  provider: ^6.1.5+1
  dio: ^5.10.0
  retrofit: ^4.10.0
  cupertino_icons: ^1.0.8
  shimmer_animation: ^2.2.2+1
  bottom_navigator: ^0.0.5
  intl: ^0.20.3
  lottie: ^3.5.1
  shared_preferences: ^2.5.5
  sqflite: ^2.4.3
  path: ^1.9.1
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  json_serializable: ^6.14.1
  retrofit_generator: ^10.2.1   # ← cek versi terbaru di pub.dev, sesuaikan

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/
    - assets/images/ghibli/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700



